### ISSUE TITLE
[1.181016.0] Snapshot not showing GP values

### ISSUE THREAD

**Issue by DarkPhoenixSniper** [PopGoesTheWza/swgoh-tb-sheets#10]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - [Instructions Manual](https://docs.google.com/document/d/1InDnFdYdlRDpejeiFkGi6HxMEWmBbfX_wAvWRf1MCME/edit?usp=sharing)
      Discord server - https://discord.gg/ywzJEaQ

✔ Enhancements → Be specific. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable.

### Title (Put in field above)
Use the format: [version] Short description
i.e. [1.181011.0] On tab "Search Units" sort order is wrond

### Steps to reproduce
Any member and updat

### Expected Result
Shows the GP values from
roster spreadsheet for user

### Actual Result
#NUM!

### Version
1.181016.0

### Testcase
Provide a link to a copy of the TB Sheets if necessary

**Comment by PopGoesTheWza** [comment]
This feature being broken for so long (as it was not easy to grab until recently), I'll treat this as an enhancement.
- Implementation for guild members should be straightforward
- For external snapshot:
1. use ally code rather than SwgohHelp url
1. use currently active data source (i.e. .help or .gg)

**Comment by PopGoesTheWza** [comment]
Ready for next release.
